// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE1rjo306A7vbqfbwMtDjN7IRSNUTQdNo',
    appId: '1:386135674416:web:e5535c2c8e031e1e5867f5',
    messagingSenderId: '386135674416',
    projectId: 'dewdrop-a17a5',
    authDomain: 'dewdrop-a17a5.firebaseapp.com',
    storageBucket: 'dewdrop-a17a5.appspot.com',
    measurementId: 'G-44X3KZCKZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlvWTvrvk9DwoYu7-yjgxhVg9atauLJ9A',
    appId: '1:386135674416:android:32676ee1e2e334535867f5',
    messagingSenderId: '386135674416',
    projectId: 'dewdrop-a17a5',
    storageBucket: 'dewdrop-a17a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgLb7XDniNT0HVA8l_7bgYXV19jmDAZa0',
    appId: '1:386135674416:ios:750044677b5cfcd25867f5',
    messagingSenderId: '386135674416',
    projectId: 'dewdrop-a17a5',
    storageBucket: 'dewdrop-a17a5.appspot.com',
    iosClientId: '386135674416-nrtcruj02uijbsjfr7n5uaml2t2tq1qd.apps.googleusercontent.com',
    iosBundleId: 'com.example.dewdrop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgLb7XDniNT0HVA8l_7bgYXV19jmDAZa0',
    appId: '1:386135674416:ios:750044677b5cfcd25867f5',
    messagingSenderId: '386135674416',
    projectId: 'dewdrop-a17a5',
    storageBucket: 'dewdrop-a17a5.appspot.com',
    iosClientId: '386135674416-nrtcruj02uijbsjfr7n5uaml2t2tq1qd.apps.googleusercontent.com',
    iosBundleId: 'com.example.dewdrop',
  );
}
